# Generated by Django 3.2 on 2021-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0003_server_app_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='server_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='ansibleexechistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ansibleexectemplate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ansiblesyncfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cloudak',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecsauthssh',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='securitygroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
