# Generated by Django 3.2 on 2021-10-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0004_auto_20211013_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbconnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dbtype', models.CharField(blank=True, choices=[('mysql', 'mysql数据库'), ('oracle', 'oracle数据库'), ('sqlserver', 'sqlserver数据库')], max_length=32, verbose_name='数据库类型')),
                ('dbname', models.CharField(blank=True, max_length=64, verbose_name='数据库名称')),
                ('connstr', models.CharField(blank=True, max_length=256, verbose_name='连接字符串')),
                ('dbdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='业务系统描述')),
            ],
        ),
    ]
