# Generated by Django 3.2 on 2021-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0007_auto_20211015_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlstatement',
            name='sqlname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='sql名称'),
        ),
        migrations.AddField(
            model_name='sqlstatement',
            name='sqlpriv',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='sql执行所需django权限'),
        ),
    ]
