# Generated by Django 3.2 on 2021-10-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0008_auto_20211015_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlstatement',
            name='sqlname',
            field=models.CharField(blank=True, default='haha', max_length=64, verbose_name='sql名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sqlstatement',
            name='sqlstr',
            field=models.CharField(blank=True, max_length=21000, verbose_name='sql字符串'),
        ),
    ]
