# Generated by Django 3.2 on 2021-10-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0010_alter_sqlstatement_sqlstr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepermission',
            options={'permissions': (('killblocker', 'Can kill blocker'), ('viewebs', 'Can view ebs locker'), ('viewhr', 'Can view hr locker'), ('activesession', 'Can view activesession'), ('dbconnection', 'Can modify dbconnection'), ('sqlconfig', 'Can modify sql statement'), ('sqlexec', 'Can exec sql statement'))},
        ),
    ]
