# Generated by Django 3.2 on 2021-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0011_alter_pagepermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminsql',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dbtype', models.CharField(blank=True, choices=[('mysql', 'mysql数据库'), ('oracle', 'oracle数据库'), ('sqlserver', 'sqlserver数据库')], max_length=32, verbose_name='数据库类型')),
                ('sqlname', models.CharField(blank=True, max_length=64, verbose_name='sql名称')),
                ('sqlstr', models.CharField(blank=True, max_length=21000, verbose_name='sql字符串')),
                ('sqlpriv', models.CharField(blank=True, max_length=256, null=True, verbose_name='sql执行所需django权限')),
                ('sqldesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='sql执行描述')),
            ],
        ),
    ]
