# Generated by Django 3.2 on 2021-11-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0012_adminsql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='app_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='应用id'),
        ),
    ]
