# Generated by Django 3.2 on 2021-11-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0013_alter_server_app_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepermission',
            options={'permissions': (('killblocker', 'Can kill blocker'), ('viewebs', 'Can view ebs locker'), ('viewhr', 'Can view hr locker'), ('activesession', 'Can view activesession'), ('dbconnection', 'Can modify dbconnection'), ('sqlconfig', 'Can modify sql statement'), ('sqlexec', 'Can exec sql statement'), ('appstartstop', 'Can start and stop app'), ('wikirestart', 'Can start and stop wiki'))},
        ),
        migrations.AddField(
            model_name='app',
            name='apppriv',
            field=models.CharField(blank=True, max_length=64, verbose_name='app管理权限'),
        ),
    ]
