# Generated by Django 3.2 on 2021-11-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0014_auto_20211114_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ansibletasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='应用id')),
                ('playbook', models.CharField(blank=True, max_length=128, null=True, verbose_name='playbook名称')),
                ('ansiblepriv', models.CharField(blank=True, max_length=256, null=True, verbose_name='执行ansible脚本所需django权限')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='脚本描述')),
            ],
        ),
    ]
