# Generated by Django 3.2 on 2021-11-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0016_alter_pagepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepermission',
            options={'permissions': (('killblocker', 'Can kill blocker'), ('viewebs', 'Can view ebs locker'), ('viewhr', 'Can view hr locker'), ('activesession', 'Can view activesession'), ('dbconnection', 'Can modify dbconnection'), ('sqlconfig', 'Can modify sql statement'), ('sqlexec', 'Can exec sql statement'), ('appstartstop', 'Can start and stop app'), ('wikirestart', 'Can start and stop wiki'), ('nomadadmin', 'Can admin nomad servers'), ('ebsclone', 'Can clone ebs'))},
        ),
    ]
