# Generated by Django 3.2 on 2021-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0017_alter_pagepermission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletasks',
            name='extravars',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='playboo所带的参数'),
        ),
    ]
