# Generated by Django 3.2 on 2021-12-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0022_alter_pagepermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='grafanareports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='应用id')),
                ('reportname', models.CharField(blank=True, max_length=128, null=True, verbose_name='report名称')),
                ('extravars', models.CharField(blank=True, max_length=256, null=True, verbose_name='report所带的参数')),
                ('ansiblepriv', models.CharField(blank=True, max_length=256, null=True, verbose_name='查看报表所需django权限')),
                ('reportlink', models.CharField(blank=True, max_length=1024, null=True, verbose_name='报表url')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='报表描述')),
            ],
        ),
    ]
