# Generated by Django 3.2 on 2021-12-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyops', '0024_alter_pagepermission_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grafanareports',
            old_name='ansiblepriv',
            new_name='grafanapriv',
        ),
    ]
